[versions]
# Testing
junit-jupiter = "5.12.1"
mockito = "5.19.0"
# Logging
slf4j-api = "2.0.17"
logback-classic = "1.5.18"
# Annotation Processing
lombok = "1.18.38"
# General Utilities
commons-lang3 = "3.18.0"
commons-io = "2.20.0"
guava = "33.4.8-jre"
# JSON
jackson = "2.20.0"
org-json = "20250517"

[libraries]
# Testing
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
# Logging
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
# Annotation Processing
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
# General utilities
guava = { module = "com.google.guava:guava", version.ref = "guava" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
# JSON
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
org-json = { module = "org.json:json", version.ref = "org-json" }

[bundles]
testing = ["junit-jupiter", "mockito-core", "mockito-junit-jupiter"]
logging = ["slf4j-api", "logback-classic"]
generalUtilities = ["commons-lang3", "commons-io", "guava"]
json = ["jackson-databind", "org-json"]
