services:
  # A Kafka broker service in KRaft mode also acts as a controller
  kafka:
    image: "apache/kafka:4.1.1"
    ports:
      - '${KAFKA_PORT}:9092'
    environment:
      # Each broker must have a unique ID
      KAFKA_NODE_ID: 1
      # Roles for KRaft: broker, controller, or both
      KAFKA_PROCESS_ROLES: broker,controller
      # Internal and controller listeners
      KAFKA_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://localhost:9093"
      # Advertised listener is what clients use to connect
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      # Maps listener names to security protocols
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # Quorum voters define all nodes in the KRaft quorum
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      # Storage Configuration
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      #      test: [ "CMD-SHELL", "netstat -tlnp | grep :9092" ]
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092" ]
      interval: 5s
      timeout: 5s
      retries: 5
  kafdrop:
    image: "obsidiandynamics/kafdrop:4.2.0"
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms32M -Xmx64M"
  kafbat-ui:
    image: "ghcr.io/kafbat/kafka-ui:v1.4.2"
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: wizard_test
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

volumes:
  kafka_data:
